services:
  yoghurt-backend:
    build: .
    container_name: yoghurt_backend
    network_mode: "host"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/yoghurt
